module Database.Icon exposing (Icon(..))

{-| Corresponding images are found in the [img/Skill](../../img/Skill/) folder.
Every Icon is the name of an image file prefixed with 'Icon'. For example,
`IconAllUp` corresponds to `AllUp.png`. -}
type Icon
    = AllUp
    | ArtsCrit
    | ArtsQuickUp
    | ArtsUp
    | Avenger
    | BeamUp
    | BeamDown
    | BlueStar
    | BoxLarge
    | BoxSmall
    | Bubbles
    | Bullseye
    | BusterArtsUp
    | BusterStar
    | BusterUp
    | Cards
    | Circuits
    | ClockSkull
    | ClockUp
    | CrosshairUp
    | Crystal
    | DamageUp
    | Dash
    | Diamonds
    | Dodge
    | Eclipse
    | ExclamationUp
    | ExclamationDown
    | Face
    | Fire
    | FireDown
    | FireUp
    | Flex
    | Flower
    | Goddess
    | Heal
    | HealTurn
    | HealUp
    | Heart
    | HoodUp
    | HoodDown
    | HoodX
    | Horse
    | HPUp
    | Kneel
    | Leap
    | MagicCircle
    | MagicDark
    | MagicLight
    | Mask
    | Missing
    | Moon
    | Mystic
    | Niffin
    | Noble
    | NobleRedUp
    | NobleTurn
    | NobleUp
    | Ocean
    | Poison
    | PoisonUp
    | Potion
    | QuickBusterUp
    | QuickUp
    | Rainbow
    | ReaperUp
    | Road
    | Scar
    | Shield
    | ShieldBreak
    | ShieldDown
    | ShieldUp
    | Spotlight
    | StaffUp
    | Star
    | StarDown
    | StarHaloUp
    | StarTurn
    | StarUp
    | Stun
    | SwordDown
    | SwordPlus
    | SwordUp
    | SwordShieldUp
    | SwordsBlue
    | SwordsRed
    | Sun
    | SunUp
    | Teeth
    | Wave
    | YinYang
